NAVIGATION = {
    "/ecomomy/econom": {
        "main": "/ecomomy/econom/index.html",
        "subpages": ["/ecomomy/econom/d01.html", "/ecomomy/econom/d02.html", "/ecomomy/econom/d03.html",
                     "/ecomomy/econom/d05.html", "/ecomomy/econom/d04.html", "/ecomomy/econom/d06.html",
                     "/ecomomy/econom/d07.html","/ecomomy/econom/d08.html", "/ecomomy/econom/d09.html",
                     "/ecomomy/econom/d10.html", "/ecomomy/econom/d11.html", "/ecomomy/econom/d12.html",
                     "/ecomomy/econom/d13a.html", "/ecomomy/econom/d13b.html", "/ecomomy/econom/d13c.html",
                     "/ecomomy/econom/d14.html", "/ecomomy/econom/d15.html", "/ecomomy/econom/d16.html",
                     "/ecomomy/econom/d17.html",
                     "/ecomomy/econom/d18.html", "/ecomomy/econom/d19.html", "/ecomomy/econom/d20.html",
                     "/ecomomy/econom/d21.html",
                     "/ecomomy/econom/d22.html", "/ecomomy/econom/d23.html", "/ecomomy/econom/d24.html",
                     "/ecomomy/econom/d25.html",
                     "/ecomomy/econom/d26a.html", "/ecomomy/econom/d26b.html", "/ecomomy/econom/d26c.html",
                     "/ecomomy/econom/d27.html",
                     "/ecomomy/econom/d28.html", "/ecomomy/econom/d29.html", "/ecomomy/econom/d30a.html",
                     "/ecomomy/econom/d30b.html",
                     "/ecomomy/econom/d30c.html", "/ecomomy/econom/d30d.html", "/ecomomy/econom/d30e.html",
                     "/ecomomy/econom/d31.html",
                     "/ecomomy/econom/P1.html", "/ecomomy/econom/P2.html", "/ecomomy/econom/33.html",
                     "/ecomomy/econom/P4.html", "/ecomomy/econom/P5.html"]
    },
    "/ecomomy/pris": {
        "main": "/ecomomy/prisyaghnye.html",
        "subpages": [
                "/ecomomy/pris/0_1.html",
                "/ecomomy/pris/0_2.html",
                "/ecomomy/pris/0_3.html",
                "/ecomomy/pris/0_5.html",
                "/ecomomy/pris/0_6.html",
                "/ecomomy/pris/0_7.html",
                "/ecomomy/pris/0_8.html",
                "/ecomomy/pris/0_9.html",
                "/ecomomy/pris/1_1.html",
                "/ecomomy/pris/1_3.html",
                "/ecomomy/pris/1_4.html",
                "/ecomomy/pris/1_5.html",
                "/ecomomy/pris/1_6.html",
                "/ecomomy/pris/1_7.html",
                "/ecomomy/pris/1_8.html",
                "/ecomomy/pris/2_1.html",
                "/ecomomy/pris/2_3.html",
                "/ecomomy/pris/2_4.html",
                "/ecomomy/pris/2_5.html",
                "/ecomomy/pris/2_6.html",
                "/ecomomy/pris/3_1.html",
                "/ecomomy/pris/3_2.html",
                "/ecomomy/pris/3_3.html",
                "/ecomomy/pris/3_4.html",
                "/ecomomy/pris/3_5.html",
                "/ecomomy/pris/3_6.html",
                "/ecomomy/pris/3_7.html",
                "/ecomomy/pris/4_1.html",
                "/ecomomy/pris/4_3.html",
                "/ecomomy/pris/4_4.html",
                "/ecomomy/pris/4_5.html",
                "/ecomomy/pris/4_6.html",
                "/ecomomy/pris/4_7.html",
                "/ecomomy/pris/5_1.html",
                "/ecomomy/pris/5_3.html",
                "/ecomomy/pris/5_4.html",
                "/ecomomy/pris/5_5.html",
                "/ecomomy/pris/5_6.html",
                "/ecomomy/pris/6_1.html",
                "/ecomomy/pris/6_2.html",
                "/ecomomy/pris/6_3.html",
                "/ecomomy/pris/6_4.html",
                "/ecomomy/pris/7_1.html",
                "/ecomomy/pris/7_3.html",
                "/ecomomy/pris/7_4.html",
                "/ecomomy/pris/7_5.html",
                "/ecomomy/pris/7_6.html",
                "/ecomomy/pris/7_7.html",
                "/ecomomy/pris/7_8.html",
                "/ecomomy/pris/7_9.html",
                "/ecomomy/pris/8_1.html",
                "/ecomomy/pris/8_2.html",
                "/ecomomy/pris/8_3.html",
                "/ecomomy/pris/8_4.html",
                "/ecomomy/pris/8_5.html",
                "/ecomomy/pris/8_6.html",
                "/ecomomy/pris/8_7.html",
                "/ecomomy/pris/8_8.html"
        ]
    }
}
