NAVIGATION = {
    "/ecomomy/econom": {
        "main": "/ecomomy/econom/index.html",
        "subpages": ["/ecomomy/econom/d01.html", "/ecomomy/econom/d02.html", "/ecomomy/econom/d03.html",
                     "/ecomomy/econom/d05.html", "/ecomomy/econom/d04.html", "/ecomomy/econom/d06.html",
                     "/ecomomy/econom/d07.html","/ecomomy/econom/d08.html", "/ecomomy/econom/d09.html",
                     "/ecomomy/econom/d10.html", "/ecomomy/econom/d11.html", "/ecomomy/econom/d12.html",
                     "/ecomomy/econom/d13a.html", "/ecomomy/econom/d13b.html", "/ecomomy/econom/d13c.html",
                     "/ecomomy/econom/d14.html", "/ecomomy/econom/d15.html", "/ecomomy/econom/d16.html",
                     "/ecomomy/econom/d17.html",
                     "/ecomomy/econom/d18.html", "/ecomomy/econom/d19.html", "/ecomomy/econom/d20.html",
                     "/ecomomy/econom/d21.html",
                     "/ecomomy/econom/d22.html", "/ecomomy/econom/d23.html", "/ecomomy/econom/d24.html",
                     "/ecomomy/econom/d25.html",
                     "/ecomomy/econom/d26a.html", "/ecomomy/econom/d26b.html", "/ecomomy/econom/d26c.html",
                     "/ecomomy/econom/d27.html",
                     "/ecomomy/econom/d28.html", "/ecomomy/econom/d29.html", "/ecomomy/econom/d30a.html",
                     "/ecomomy/econom/d30b.html",
                     "/ecomomy/econom/d30c.html", "/ecomomy/econom/d30d.html", "/ecomomy/econom/d30e.html",
                     "/ecomomy/econom/d31.html",
                     "/ecomomy/econom/P1.html", "/ecomomy/econom/P2.html", "/ecomomy/econom/33.html",
                     "/ecomomy/econom/P4.html", "/ecomomy/econom/P5.html"]
    },
    "/ecomomy/pris": {
        "main": "/ecomomy/prisyaghnye.html",
        "subpages": [
                "/ecomomy/pris/0_1.html",
                "/ecomomy/pris/0_2.html",
                "/ecomomy/pris/0_3.html",
                "/ecomomy/pris/0_5.html",
                "/ecomomy/pris/0_6.html",
                "/ecomomy/pris/0_7.html",
                "/ecomomy/pris/0_8.html",
                "/ecomomy/pris/0_9.html",
                "/ecomomy/pris/1_1.html",
                "/ecomomy/pris/1_3.html",
                "/ecomomy/pris/1_4.html",
                "/ecomomy/pris/1_5.html",
                "/ecomomy/pris/1_6.html",
                "/ecomomy/pris/1_7.html",
                "/ecomomy/pris/1_8.html",
                "/ecomomy/pris/2_1.html",
                "/ecomomy/pris/2_3.html",
                "/ecomomy/pris/2_4.html",
                "/ecomomy/pris/2_5.html",
                "/ecomomy/pris/2_6.html",
                "/ecomomy/pris/3_1.html",
                "/ecomomy/pris/3_2.html",
                "/ecomomy/pris/3_3.html",
                "/ecomomy/pris/3_4.html",
                "/ecomomy/pris/3_5.html",
                "/ecomomy/pris/3_6.html",
                "/ecomomy/pris/3_7.html",
                "/ecomomy/pris/4_1.html",
                "/ecomomy/pris/4_3.html",
                "/ecomomy/pris/4_4.html",
                "/ecomomy/pris/4_5.html",
                "/ecomomy/pris/4_6.html",
                "/ecomomy/pris/4_7.html",
                "/ecomomy/pris/5_1.html",
                "/ecomomy/pris/5_3.html",
                "/ecomomy/pris/5_4.html",
                "/ecomomy/pris/5_5.html",
                "/ecomomy/pris/5_6.html",
                "/ecomomy/pris/6_1.html",
                "/ecomomy/pris/6_2.html",
                "/ecomomy/pris/6_3.html",
                "/ecomomy/pris/6_4.html",
                "/ecomomy/pris/7_1.html",
                "/ecomomy/pris/7_3.html",
                "/ecomomy/pris/7_4.html",
                "/ecomomy/pris/7_5.html",
                "/ecomomy/pris/7_6.html",
                "/ecomomy/pris/7_7.html",
                "/ecomomy/pris/7_8.html",
                "/ecomomy/pris/7_9.html",
                "/ecomomy/pris/8_1.html",
                "/ecomomy/pris/8_2.html",
                "/ecomomy/pris/8_3.html",
                "/ecomomy/pris/8_4.html",
                "/ecomomy/pris/8_5.html",
                "/ecomomy/pris/8_6.html",
                "/ecomomy/pris/8_7.html",
                "/ecomomy/pris/8_8.html"
        ]
    },
    "/ecomomy/Zes1": {
        "main": "/ecomomy/Zes1/index.html",
        "subpages": [
            "/ecomomy/Zes1/0.1.html",
            "/ecomomy/Zes1/1.1.html",
            "/ecomomy/Zes1/1.2.html",
            "/ecomomy/Zes1/1.3.html",
            "/ecomomy/Zes1/2.1.01.html",
            "/ecomomy/Zes1/2.1.02.html",
            "/ecomomy/Zes1/2.1.03.html",
            "/ecomomy/Zes1/2.1.04.html",
            "/ecomomy/Zes1/2.1.05.html",
            "/ecomomy/Zes1/2.1.06.html",
            "/ecomomy/Zes1/2.1.07.html",
            "/ecomomy/Zes1/2.1.08.html",
            "/ecomomy/Zes1/2.1.09.html",
            "/ecomomy/Zes1/2.1.10.html",
            "/ecomomy/Zes1/2.1.11.html",
            "/ecomomy/Zes1/3.01.html",
            "/ecomomy/Zes1/3.02.html",
            "/ecomomy/Zes1/3.03.html",
            "/ecomomy/Zes1/3.04.html",
            "/ecomomy/Zes1/3.05.html",
            "/ecomomy/Zes1/3.05.html",
            "/ecomomy/Zes1/3.06.html",
            "/ecomomy/Zes1/3.07.html",
            "/ecomomy/Zes1/3.08.html",
            "/ecomomy/Zes1/3.09.html",
            "/ecomomy/Zes1/3.10.html",
            "/ecomomy/Zes1/3.11.html",
            "/ecomomy/Zes1/4.1.html"
        ]
    },
    "/ecomomy/Zes2": {
        "main": "/ecomomy/Zes2/index.html",
        "subpages": [
            "/ecomomy/Zes2/0.1.html",
            "/ecomomy/Zes2/I.1.html",
            "/ecomomy/Zes2/I.2.html",
            "/ecomomy/Zes2/I.3.html",
            "/ecomomy/Zes2/I.4.html",
            "/ecomomy/Zes2/I.5.html",
            "/ecomomy/Zes2/I.6.html",
            "/ecomomy/Zes2/II.1.html",
            "/ecomomy/Zes2/I.2.html",
            "/ecomomy/Zes2/II.3.html",
            "/ecomomy/Zes2/III.html",
            "/ecomomy/Zes2/IV.1.html",
            "/ecomomy/Zes2/IV.2.html",
            "/ecomomy/Zes2/IV.3.html",
            "/ecomomy/Zes2/V.1.html",
            "/ecomomy/Zes2/V.2.html",
            "/ecomomy/Zes2/V.3.html",
            "/ecomomy/Zes2/V.4.html",
            "/ecomomy/Zes2/V.5.html"
        ]
    },
    "/ecomomy/Zes3": {
        "main": "/ecomomy/Zes3/index.html",
        "subpages": [
            "/ecomomy/Zes3/0.1.html",
            "/ecomomy/Zes3/1.1.html",
            "/ecomomy/Zes3/1.2.html",
            "/ecomomy/Zes3/2.1.html",
            "/ecomomy/Zes3/3.1.html",
            "/ecomomy/Zes3/3.2.html",
            "/ecomomy/Zes3/4.1.html"
        ]
    },
    "/ecomomy/Zes4": {
        "main": "/ecomomy/Zes4/index.html",
        "subpages": [
            "/ecomomy/Zes4/0.0.html",
            "/ecomomy/Zes4/41.1.html",
            "/ecomomy/Zes4/41.2.html",
            "/ecomomy/Zes4/42.1.html",
            "/ecomomy/Zes4/43.1.html",
            "/ecomomy/Zes4/45.1.html",
            "/ecomomy/Zes4/45.2.html",
            "/ecomomy/Zes4/46.1.html",
            "/ecomomy/Zes4/46.2.html"
        ]
    },
    "/ecomomy/Zes5": {
        "main": "/ecomomy/Zes5/index.html",
        "subpages": [
            "/ecomomy/Zes5/0.1.html",
            "/ecomomy/Zes5/51.1.html",
            "/ecomomy/Zes5/51.2.html",
            "/ecomomy/Zes5/52.1.html",
            "/ecomomy/Zes5/53.1.html",
            "/ecomomy/Zes5/55.1.html",
            "/ecomomy/Zes5/55.2.html",
            "/ecomomy/Zes5/56.1.html"
        ]
    },
    "/ecomomy/Zes6": {
        "main": "/ecomomy/Zes6/index.html",
        "subpages": [
            "/ecomomy/Zes6/0.0.html",
            "/ecomomy/Zes6/61.1.html",
            "/ecomomy/Zes6/62.1.html",
            "/ecomomy/Zes6/63.1.html",
            "/ecomomy/Zes6/64.1.html",
            "/ecomomy/Zes6/65.1.html"
        ]
    },
    "/ecomomy/Zes7": {
        "main": "/ecomomy/Zes7/index.html",
        "subpages": [
            "/ecomomy/Zes7/7.0.html",
            "/ecomomy/Zes7/71.2.html",
            "/ecomomy/Zes7/72.1.html",
            "/ecomomy/Zes7/72.2.html",
            "/ecomomy/Zes7/72.3.html",
            "/ecomomy/Zes7/72.4.html",
            "/ecomomy/Zes7/72.5.html",
            "/ecomomy/Zes7/72.6.html"
        ]
    }

}
